# Generated by Django 5.1.1 on 2024-10-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_desc',
            new_name='course_description',
        ),
    ]
