# Generated by Django 5.1.1 on 2024-12-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_remove_submission_feedback_remove_submission_grade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='grade',
        ),
    ]
