# Generated by Django 5.1.1 on 2024-12-20 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_delete_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.course'),
        ),
    ]
