# Generated by Django 5.1.1 on 2024-12-27 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0012_lessons_module_delete_course_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="classroom.course",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="classroom.course",
            ),
        ),
    ]
