# Generated by Django 5.1.1 on 2024-12-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0013_alter_lessons_course_alter_module_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="order",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=models.IntegerField(null=True),
        ),
    ]
