# Generated by Django 5.1.1 on 2024-12-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_author_author_book_author_alter_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
